### PR TITLE
Homepage

### PR DESCRIPTION
**Pull request by DariBerrie**
Created a homepage from the Pages views (home.html.erb) just in case per Kurt's recommendations!

### CODE REVIEW

**Review by AmandaPerino — COMMENTED** [review]
Same comment about the order association.

**Review by AmandaPerino — APPROVED** [review]
All looks good if we are keeping the 1-to-1 association between Orders and Products.

**Comment by DariBerrie** [comment]
Should have included a screenshot 😅
Screen Shot 2022-10-31 at 14 55 39

**Comment by AmandaPerino** [comment]
@DariBerrie mind if I merge this? I think it is quite connected to my work today (nav bar and footer).

**Comment by DariBerrie** [comment]
@AmandaPerino Yeah go ahead!

**Pull request merged**
