### PR TITLE
Show html erb

### PR DESCRIPTION
**Pull request by DariBerrie**
I mainly updated the show.html.erb view, but I played around with some of the SCSS to help style the page. I also noticed that the previous SCSS done for Pages#home.html.erb was lost so I tried to update it, but I don't think I got everything right @PiotrekCodes let me know if any changes need to be made there. (The map is just an image, so don't get too excited!)

🚨 In an effort to make the page look less empty, I added some product model attributes like "title" and "description" to the show page, but I didn't add them "officially" in the model. 

Screen Shot 2022-11-02 at 13 00 21

### CODE REVIEW

**Review by AmandaPerino — APPROVED** [review]
This looks really good @DariBerrie. The only change I don't quite get is on the application.scss stylesheet as it says there is a conflict there, but if it is working on your local machine, I trust the process!

**Comment by DariBerrie** [comment]
Yeah, it was the application.html.erb file...It was causing issues for me because of turbo, but the missing line was needed to make the javascript work so I added it back in. It should be fine now 🤞

**Comment by PiotrekCodes** [comment]
I really like it, my only 'concern'/thinking ahead is that we will be told maps takes too much space, and it takes the eyes off more important things. I might be wrong, though.

**Comment by DariBerrie** [comment]
Alternative view with less of a focus on the map. Let me know what you guys think! (I haven't pushed this just in case we prefer the first option)
Screen Shot 2022-11-02 at 13 00 21

**Review by zynolia — APPROVED** [review]
Thank Dari, looks good! I prefer the first one, for me that layout is more balanced

**Comment by DariBerrie** [comment]
Popping the code for the second version here just in case.
```
<div class="container">
    <div class="row justify-content-center">
      <div class="col-5 carousel-container">
        <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
          <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
          </div>
          <div class="carousel-inner">
            <div class="carousel-item active shadow">
              <img id="carousel_image" src="https://images.unsplash.com/photo-1588676006059-956f7751dc31?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1974&q=80"
              class="d-block w-100 rounded-4" alt="...">
            </div>
            <div class="carousel-item shadow">
              <img id="carousel_image" src="https://images.unsplash.com/photo-1588676081834-24a928659998?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1974&q=80"
              class="d-block w-100 rounded-4" alt="...">
            </div>
            <div class="carousel-item shadow">
              <img id="carousel_image" src="https://images.unsplash.com/photo-1588676006059-956f7751dc31?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1974&q=80"
              class="d-block w-100 rounded-4" alt="...">
            </div>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
        <div class="row justify-content-center">
          <p class="fw-bold text-center mt-3">Check out more things by <%= @product.brand %></p>
          <div class="recommendations-container d-flex justify-content-center">
            <img src="https://images.unsplash.com/photo-1588676006059-956f7751dc31?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1974&q=80"
                class="p-0 me-2 rounded-4"
                style="width:150px; height:100px;object-fit:cover;">
            <img src="https://images.unsplash.com/photo-1588676006059-956f7751dc31?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1974&q=80"
                class="p-0 me-2 rounded-4"
                style="width:150px; height:100px;object-fit:cover;">
            <img src="https://images.unsplash.com/photo-1588676006059-956f7751dc31?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1974&q=80"
            class="p-0 rounded-4"
            style="width:150px; height:100px;object-fit:cover;">
          </div>
          <div class="user-container d-flex flex-row justify-content-center align-items-center mt-3">
              <img src="https://res.cloudinary.com/wagon/image/upload/c_fill,g_face,h_200,w_200/v1657958011/sxovr5ewgezo8xl6xpcy.jpg"
                  class="avatar-large" alt="">
              <div class="user-links-container d-flex flex-column">
                <div class="user-star-rating">
                  <p class="fw-bold my-0 ms-3"><%= @product.user.first_name %>
                  <span class="ms-2"><% 5.times do %><i class="fa-solid fa-star text-warning"></i><% end %></span></p>
                </div>
                <% if @product.user == current_user %>
                  <%= link_to "See your stash", root_path, class: "btn btn-primary rounded-3 ms-3 text-white" %>
                <% else %>
                  <%= link_to "See their stash", root_path, class: "btn btn-primary rounded-3 ms-3 text-white" %>
                <% end %>
              </div>
            </div>
        </div>
      </div>
      <div class="col-5 description-container d-flex flex-column">
        <div class="description-container">
          <h2>Temporary Title</h2>
          <h3 class="fw-bold"><%= @product.price %>€</h3>
          <h3 class="fw-bold"><%= @product.name %></h3>
          <h3><%= @product.brand %></h3>
          <p><strong>Yarn weight:</strong> <%= @product.weight %>
          <br><strong>Composition:</strong> <%= @product.material %>
          <br><strong>Color:</strong> <%= @product.color %></p>
          <p class="pe-5">This is a description. This yarn is really great And is an amazing color. I wish I could have made something with it.
          But alas, it's not meant to be. I'd like these skeins to find a new home.</p>
          <%= link_to "Buy now", root_path, class: "btn btn-success rounded-3 fw-bold text-white" %>
        </div>
        <div class="map-container mt-3">
          <img id="map" src='https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/2.3381,48.8693,10.45,0,0/500x250?access_token=pk.eyJ1IjoiZGFyaWdvbGRtYW4iLCJhIjoiY2w4YWpobmFvMDZtYTQxcXFydXU5NXBmeSJ9.24yAwCQ8yKfvtKXcC0RMjg'
          class="rounded-4 shadow"
          style="height:250px;width:500px;">
        </div>
    </div>
  </div>
  </div>
</div>
```

**Comment by DariBerrie** [comment]
Okay, so this is the latest version. I took the first version, but needed to incorporate some of the 2nd in order to be more responsive for mobile. I wasn't able to align the "avatar card" to the right...if anyone has any ideas, I'm all ears.

Screen Shot 2022-11-03 at 17 10 02

**Pull request merged**
